<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.1 (Python 3.7.2 on darwin)" generated="20190420 10:40:43.043" rpa="false">
<suite id="s1" name="Demo" source="/Users/monica.danesa/Documents/mykonos/demo">
<suite id="s1-s1" name="Test Open Apps" source="/Users/monica.danesa/Documents/mykonos/demo/test_open_apps.robot">
<test id="s1-s1-t1" name="Test Open Apps">
<kw name="Log" library="BuiltIn">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>Test</arg>
</arguments>
<msg timestamp="20190420 10:40:43.066" level="INFO">Test</msg>
<status status="PASS" starttime="20190420 10:40:43.066" endtime="20190420 10:40:43.066"></status>
</kw>
<status status="PASS" starttime="20190420 10:40:43.066" endtime="20190420 10:40:43.066" critical="yes"></status>
</test>
<status status="PASS" starttime="20190420 10:40:43.063" endtime="20190420 10:40:43.067"></status>
</suite>
<status status="PASS" starttime="20190420 10:40:43.045" endtime="20190420 10:40:43.067"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" id="s1" name="Demo">Demo</stat>
<stat pass="1" fail="0" id="s1-s1" name="Test Open Apps">Demo.Test Open Apps</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20190420 10:40:43.065" level="ERROR">Error in file '/Users/monica.danesa/Documents/mykonos/demo/test_open_apps.robot': Importing test library 'mykonos' failed: ModuleNotFoundError: No module named 'mykonos'
Traceback (most recent call last):
  None
PYTHONPATH:
  /Users/monica.danesa/.local/share/virtualenvs/mykonos-3UDsd9FA/bin
  /Users/monica.danesa/.local/share/virtualenvs/mykonos-3UDsd9FA/lib/python37.zip
  /Users/monica.danesa/.local/share/virtualenvs/mykonos-3UDsd9FA/lib/python3.7
  /Users/monica.danesa/.local/share/virtualenvs/mykonos-3UDsd9FA/lib/python3.7/lib-dynload
  /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7
  /Users/monica.danesa/.local/share/virtualenvs/mykonos-3UDsd9FA/lib/python3.7/site-packages</msg>
</errors>
</robot>
